### ISSUE TITLE
Crash in DriverStation thread

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpilib#139]
```
Exception in thread FRCDriverStation:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/threading.py", line 921, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.4/threading.py", line 869, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/site-packages/wpilib/driverstation.py", line 111, in task
    MotorSafety.checkMotors()
  File "/usr/local/lib/python3.4/site-packages/wpilib/motorsafety.py", line 116, in checkMotors
    for msh in MotorSafety.helpers:
  File "/usr/local/lib/python3.4/_weakrefset.py", line 60, in __iter__
    for itemref in self.data:
RuntimeError: Set changed size during iteration
```

Probably need a lock here.

**Comment by virtuald** [comment]
This bug can be easily duplicated in simulation, by changing wpilib.motorsafety.checkMotors to look like this:

```
            import time
            for msh in MotorSafety.helpers:
                time.sleep(1)
                msh.check()

```

This is a critical bug that could prevent a robot from receiving driver station data.
