### ISSUE TITLE
AttributeError when using Preferences

### ISSUE THREAD

**Issue by DrWateryCat** [robotpy/robotpy-wpilib#201]
I am using robotpy 2016.2.4, and when I try to use the wpilib.Preferences object, I get the following error and stacktrace:

```
ERROR Unhandled exception:
Traceback (most recent call last):
  File "/home/lvuser/py/robot.py", line 106, in <module>
    wpilib.run(MyRobot)
  File "/usr/local/lib/python3.5/site-packages/wpilib/_impl/main.py", line 101, in run
    retval = options.cmdobj.run(options, robot_class, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/hal/main.py", line 11, in run
    return robot_class.main(robot_class)
  File "/usr/local/lib/python3.5/site-packages/wpilib/robotbase.py", line 178, in main
    robot.startCompetition()
  File "/usr/local/lib/python3.5/site-packages/wpilib/iterativerobot.py", line 129, in startCompetition
    self.autonomousPeriodic()
  File "/home/lvuser/py/robot.py", line 62, in autonomousPeriodic
    self.autonomous.run(iter_fn=self.update_gyro)
  File "/usr/local/lib/python3.5/site-packages/robotpy_ext/autonomous/selector.py", line 231, in run
    on_exception()
  File "/usr/local/lib/python3.5/site-packages/robotpy_ext/autonomous/selector.py", line 229, in run
    self._on_iteration(timer.get())
  File "/usr/local/lib/python3.5/site-packages/robotpy_ext/autonomous/selector.py", line 273, in _on_iteration
    self.active_mode.on_iteration(time_elapsed)
  File "/usr/local/lib/python3.5/site-packages/robotpy_ext/autonomous/stateful_autonomous.py", line 463, in on_iteration
    state.run(self, tm, tm - state.start_time, initial_call)
  File "<string>", line 1, in <lambda>
  File "/home/lvuser/py/Autonomous/go_forward.py", line 21, in forward
    self.left.set(1, self.gyro, self.kP)
  File "/home/lvuser/py/Gearbox.py", line 30, in set
    self.set_with_gyro(value, gyro, kP)
  File "/home/lvuser/py/Gearbox.py", line 51, in set_with_gyro
    prefs = wpilib.Preferences.getInstance()
  File "/usr/local/lib/python3.5/site-packages/wpilib/preferences.py", line 59, in getInstance
    Preferences.instance = Preferences()
  File "/usr/local/lib/python3.5/site-packages/wpilib/preferences.py", line 85, in __init__
    reader = threading.Thread(target=self._read,
AttributeError: 'Preferences' object has no attribute '_read'
```

It looks like an internal error with the class.

**Comment by virtuald** [comment]
Fixed in #198 I believe, but I haven't made a new release... probably not going to make a new release until kickoff.
