### ISSUE TITLE
Logging exception formatting raises AttributeError in certain scenarios

### ISSUE THREAD

**Issue by auscompgeek** [robotpy/robotpy-wpilib#449]
Not entirely sure why `exc` in our `formatException` would ever be None, but uh…

Here's the traceback I get when I ^C the simulator:

```pytb
^C--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 583, in format
    record.exc_text = self.formatException(record.exc_info)
  File "~/dev/frc/robotpy/robotpy-wpilib/wpilib/wpilib/_impl/logconfig.py", line 47, in formatException
    while exc.__cause__:
AttributeError: 'NoneType' object has no attribute '__cause__'
Call stack:
  File "~/dev/frc/robotpy/robotpy-wpilib/wpilib/wpilib/_impl/main.py", line 16, in ds_except_hook
    DriverStation.reportError("ERROR Unhandled {}".format(exctype), True)
  File "~/dev/frc/robotpy/robotpy-wpilib/wpilib/wpilib/driverstation.py", line 161, in reportError
    DriverStation._reportErrorImpl(True, 1, error, printTrace)
  File "~/dev/frc/robotpy/robotpy-wpilib/wpilib/wpilib/driverstation.py", line 193, in _reportErrorImpl
    logger.exception(error)
Message: "ERROR Unhandled <class 'KeyboardInterrupt'>"
Arguments: ()
Traceback (most recent call last):
  File "./robot.py", line 129, in <module>
    wpilib.run(Robot)
  File "~/dev/frc/robotpy/robotpy-wpilib/wpilib/wpilib/_impl/main.py", line 136, in run
    retval = options.cmdobj.run(options, robot_class, **kwargs)
  File "~/dev/frc/robotpy/pyfrc/lib/pyfrc/mains/cli_sim.py", line 67, in run
    ui.run()
  File "~/dev/frc/robotpy/pyfrc/lib/pyfrc/sim/ui.py", line 427, in run
    self.root.mainloop()  # This call BLOCKS
  File "/usr/lib64/python3.6/tkinter/__init__.py", line 1277, in mainloop
    self.tk.mainloop(n)
  File "/usr/lib64/python3.6/tkinter/__init__.py", line 1694, in __call__
    def __call__(self, *args):
KeyboardInterrupt
```

**Comment by virtuald** [comment]
I had started working on this the other day. It's because of the unhandled exception handler doesn't have an exception set.
